-- Applications de location
CREATE TABLE public.rental_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id uuid NOT NULL REFERENCES public.properties(id),
  applicant_id uuid NOT NULL REFERENCES public.profiles(id),
  status application_status DEFAULT 'pending'::application_status,
  cover_letter text,
  documents jsonb DEFAULT '[]'::jsonb,
  application_score integer,
  proposed_rent integer,
  move_in_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  processing_deadline timestamp with time zone,
  guarantor_info jsonb DEFAULT '{}'::jsonb,
  employment_info jsonb DEFAULT '{}'::jsonb,
  background_check_status text DEFAULT 'pending'::text,
  credit_score integer,
  income_verification_status text DEFAULT 'pending'::text,
  reference_contacts jsonb DEFAULT '[]'::jsonb,
  previous_landlord_info jsonb DEFAULT '{}'::jsonb,
  special_requests text,
  viewing_dates timestamp with time zone[],
  pet_ownership_info jsonb DEFAULT '{}'::jsonb,
  smoking_policy_acknowledged boolean DEFAULT false,
  emergency_contact jsonb DEFAULT '{}'::jsonb,
  additional_occupants jsonb DEFAULT '[]'::jsonb,
  is_overdue boolean DEFAULT false,
  urgency_level text DEFAULT 'normal'::text,
  property_visit_scheduled boolean DEFAULT false,
  property_visit_date timestamp with time zone,
  owner_notes text,
  automated_reminders_sent integer DEFAULT 0,
  last_reminder_sent timestamp with time zone,
  internal_notes text,
  auto_processed boolean DEFAULT false,
  processing_stage text DEFAULT 'initial'::text,
  ai_score integer,
  risk_level text DEFAULT 'medium'::text,
  priority_score integer DEFAULT 0,
  matched_properties uuid[],
  automated_recommendations jsonb DEFAULT '[]'::jsonb,
  last_activity timestamp with time zone,
  follow_up_required boolean DEFAULT false,
  follow_up_date timestamp with time zone,
  communication_preferences jsonb DEFAULT '{}'::jsonb,
  budget_range jsonb DEFAULT '{}'::jsonb,
  location_preferences text[],
  amenity_preferences text[],
  accessibility_requirements text[],
  timeline_requirement text,
  move_in_flexibility boolean DEFAULT true,
  viewing_history jsonb DEFAULT '[]'::jsonb,
  application_notes text,
  document_status jsonb DEFAULT '{}'::jsonb,
  verification_status jsonb DEFAULT '{}'::jsonb,
  compliance_checks jsonb DEFAULT '{}'::jsonb,
  background_check_completed boolean DEFAULT false,
  credit_check_completed boolean DEFAULT false,
  reference_check_completed boolean DEFAULT false,
  employment_verification_completed boolean DEFAULT false,
  auto_action_type text DEFAULT 'none'::text,
  auto_action_reason text,
  auto_action_at timestamp with time zone,
  reviewed_at timestamp with time zone
);

-- Documents des applications
CREATE TABLE public.application_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES public.rental_applications(id),
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['id_card'::text, 'proof_of_income'::text, 'guaranty'::text, 'employment_contract'::text, 'bank_statement'::text, 'other'::text])),
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  mime_type text,
  verification_status text DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text, 'not_attempted'::text])),
  verified_at timestamp with time zone,
  verified_by uuid REFERENCES public.profiles(id),
  rejection_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Indexes pour les performances des applications
CREATE INDEX idx_rental_applications_property_id ON rental_applications(property_id);
CREATE INDEX idx_rental_applications_applicant_id ON rental_applications(applicant_id);
CREATE INDEX idx_rental_applications_status ON rental_applications(status);
CREATE INDEX idx_rental_applications_created_at ON rental_applications(created_at);
CREATE INDEX idx_application_documents_application_id ON application_documents(application_id);
CREATE INDEX idx_rental_applications_property_status ON rental_applications(property_id, status) WHERE status IN ('pending', 'approved');