-- Mandats d'agence
CREATE TABLE public.agency_mandates (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id uuid REFERENCES public.properties(id),
  agency_id uuid NOT NULL REFERENCES public.profiles(id),
  owner_id uuid NOT NULL REFERENCES public.profiles(id),
  mandate_number text UNIQUE,
  mandate_type text DEFAULT 'exclusive'::text,
  status text DEFAULT 'active'::text,
  start_date date NOT NULL,
  end_date date,
  renewal_terms text,
  commission_rate numeric,
  fixed_fee integer,
  exclusive_period integer,
  territory text,
  marketing_budget integer,
  responsibilities jsonb DEFAULT '{}'::jsonb,
  restrictions text[],
  signed_document_url text,
  owner_signature_url text,
  agency_signature_url text,
  notes text,
  termination_reason text,
  termination_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chk_mandate_dates CHECK (start_date <= end_date)
);