-- Paiements
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  payment_type text NOT NULL,
  amount integer NOT NULL,
  currency text DEFAULT 'XOF'::text,
  status text DEFAULT 'pending'::text,
  payment_method text,
  payment_reference text UNIQUE,
  description text,
  payer_id uuid NOT NULL REFERENCES public.profiles(id),
  recipient_id uuid NOT NULL REFERENCES public.profiles(id),
  property_id uuid REFERENCES public.properties(id),
  lease_id uuid REFERENCES public.leases(id),
  due_date date,
  paid_at timestamp with time zone,
  transaction_id text,
  external_transaction_id text,
  payment_gateway_response jsonb,
  invoice_url text,
  receipt_url text,
  refund_amount integer DEFAULT 0,
  refund_reason text,
  refunded_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chk_payment_amount CHECK (amount > 0 AND refund_amount <= amount)
);